version: '3.8'

services:
    mysql:
      image: mysql:8.0
      container_name: mysql_db
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: ROOT_MYSQL_P@ssw0rd
          MYSQL_DATABASE: image_gen_database
          MYSQL_USER: mysql_user
          MYSQL_PASSWORD: USER_MYSQL_P@ssw0rd
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data: